version: "3"

services:

  database:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis

volumes:
  postgres-data:
  redis-data:


