apiVersion: v1
kind: Service

metadata:
  name: notification-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:745263491396:certificate/09c37bae-b891-4b1d-a12a-829148846231
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ports: "443,8443"

spec:
  selector:
    app: api
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8082
    - name: https
      port: 443
      targetPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployments
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification-container
          image: 745263491396.dkr.ecr.us-east-1.amazonaws.com/trucktrace-notifications:email
            #env:
            #- name: AUTH_ADDRESS
            #value:  10.105.45.35
          #  value: auth-service.default  #domain name of service
          ports:
            - containerPort: 8082
      imagePullSecrets:
        - name: regcred


