
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-deployments
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service
  template:
    metadata:
      labels:
        app: service
    spec:
      containers:
        - name: service-container
          image: 745263491396.dkr.ecr.us-east-1.amazonaws.com/trucktrace-service:latest
          env:
            - name: ELASTIC_HOST
              value: elasticsearch-service.default
      imagePullSecrets:
        - name: regcred
