server:
  port: 8081

postgres:
  user: trucktrace
  name: trucktrace
  #host: localhost
  host: postgres
  port: 5432

redis:
  #host: localhost
  host: redis
  port: 6379
  db: 0

sms:
  apiKey: test123
  apiSecret: test123


elastic:
  #host: http://127.0.0.1
  host: http://elasticsearch
  port: 9200

email:
  host: smtp.gmail.com
  port: 587
  user: test123@gmail.com
  password: Z-9SMQ!test123?2Q-qT?juJQ=test123



  #NATS_HOST: nats://127.0.0.1
  NATS_HOST: nats://nats
  NATS_PORT: 4222


nats:
  host: nats
  #host: 127.0.0.1
  port: 4222